# Generated by Django 3.1.4 on 2021-01-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210127_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
