# Generated by Django 3.1.4 on 2021-02-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Note',
        ),
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
    ]
